version: 2
jobs:
  upload:
    docker:
      - image: node:10.8.0
    steps:
      - checkout
      - run:
          command: npm install -g surge
      - run:
          command: yarn
      - run:
          command: yarn build
      - run:
          command: yarn export
      - run:
          command: surge out uiuc.hack4impact.org
workflows:
  version: 2
  upload_job:
    jobs:
      - upload:
        filters:
            branches:
              only: master
        
